name: Zephyr OS BACnet Sample Builds
# For Zephyr 3.7 LTS, use the v0.26-branch
# or the latest v0.26.x release Docker image.
# Docker image was built on Ubuntu 22.04

on:
  push:
    branches: [ "default" ]
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  sample-hello-world:
    name: Build Hello BACnet Stack
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.18
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: bacnet
      - name: Initialize
        working-directory: bacnet
        run: |
          west init -l .
          west update
      - name: Samples - Hello World
        working-directory: bacnet
        run: |
          pwd
          west build -p always -b native_posix ./zephyr/samples/hello_bacnet_stack
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: hello_bacnet_stack
          path: bacnet/build

  sample-bacnet-profile-b-ss:
    name: Build BACnet Sample Profile B-SS
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/v0.26.18
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: bacnet
      - name: Initialize
        working-directory: bacnet
        run: |
          west init -l .
          west update
      - name: Sample - BACnet Profile B-SS
        working-directory: bacnet
        run: |
          pwd
          west build -b nucleo_f429zi -p always ./zephyr/samples/profiles/b-ss
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: b-ss
          path: bacnet/build

  sample-bacnet-profile-b-sa:
    name: Build BACnet Sample Profile B-SA
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/v0.26.18
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: bacnet
      - name: Initialize
        working-directory: bacnet
        run: |
          west init -l .
          west update
      - name: Sample - BACnet Profile B-SA
        working-directory: bacnet
        run: |
          pwd
          west build -b nucleo_f429zi -p always ./zephyr/samples/profiles/b-sa
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: b-sa
          path: bacnet/build

  sample-bacnet-profile-b-ld:
    name: Build BACnet Sample Profile B-LD
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/v0.26.18
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: bacnet
      - name: Initialize
        working-directory: bacnet
        run: |
          west init -l .
          west update
      - name: Sample - BACnet Profile B-LD
        working-directory: bacnet
        run: |
          pwd
          west build -b nucleo_f429zi -p always ./zephyr/samples/profiles/b-ld
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: b-ld
          path: bacnet/build

  sample-bacnet-profile-b-ls:
    name: Build BACnet Sample Profile B-LS
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/v0.26.18
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: bacnet
      - name: Initialize
        working-directory: bacnet
        run: |
          west init -l .
          west update
      - name: Sample - BACnet Profile B-LS
        working-directory: bacnet
        run: |
          pwd
          west build -b nucleo_f429zi -p always ./zephyr/samples/profiles/b-ls
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: b-ls
          path: bacnet/build
