name: Zephyr OS CMake

on:
  push:
    branches: [ "default" ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: bacnet

      - name: Initialize
        working-directory: bacnet
        run: |
          west init -l .
          west update

      - name: Twister Tests unit_testing
        working-directory: bacnet
        run: |
          bacnet/unittest.sh

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: bacnet/twister-out.unit_testing
