permissions:
  contents: read
name: Zephyr OS Unit Tests and Sample Builds
# For Zephyr 3.7 LTS, use the v0.26-branch
# or the latest v0.26.x release Docker image.
# Docker image was built on Ubuntu 22.04
on:
  push:
    branches: [ "default" ]
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run-image:
    runs-on: ubuntu-22.04
    permissions:
      packages: read # Required to pull private images from GHCR
    steps:
      - name: Show File System Info
        run: |
          docker system df
          docker images
      - name: Free file system space
        run: |
          echo "== Remove all unused containers, networks, images"
          echo "== (both dangling and unused), and optionally, volumes."
          set -e
          sudo docker system prune --all --filter "until=720h" --force
          docker system df
      - name: Delete unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Pull Docker image from GHCR
        run: docker pull ghcr.io/zephyrproject-rtos/ci:v0.26-branch
      - uses: actions/checkout@v6
      - name: Run Docker image from GHCR
        env:
          DOCKER_RUN_TARGET: "/workspace/bacnet/west-ci.sh && /workspace/bacnet/samples.sh && /workspace/bacnet/unittest.sh && /workspace/bacnet/subsys.sh"
          ZEPHYR_CONTAINER: "ghcr.io/zephyrproject-rtos/ci:v0.26-branch"
        run: |
          ls -alh
          echo "== Run Docker image from GHCR"
          docker run --rm -w /workspace -v "$(pwd):/workspace/bacnet" "$ZEPHYR_CONTAINER" /bin/bash -c "$DOCKER_RUN_TARGET"
      - name: Upload sample Twister results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: twister-out.samples
          path: twister-out.samples
          if-no-files-found: warn
      - name: Upload unit_testing Twister results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: twister-out.unit_testing
          path: twister-out.unit_testing
          if-no-files-found: warn
      - name: Upload subsys Twister results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: twister-out.subsys
          path: twister-out.subsys
          if-no-files-found: warn
